name: Validate TenantScript Encoding
on: 
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  ValidateEncodig:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      - name: Accent mark validator
        id: check
        uses: cjulianrivera/file-accent-validator-action@v1.3
        with:
          path: fileUTF.txt
          
      - name: Validate Encoding
        run: echo "${{ steps.check.outputs.valid }}"
